### ISSUE TITLE
+load() 方法对启动速度的影响

### ISSUE THREAD

**Issue by brave723** [youzan/Bifrost#1]
*  bindURL 方法都是在+load()方法里面执行，整个项目会有很多的+load()方法，对app启动会有一定的影响！ 这个你们有考虑？

例如：
```
+ (void)load {
    [Bifrost bindURL:kRouteShopDetail toHandler:^id _Nullable(NSDictionary * _Nullable parameters) {
        ShopDetailViewController *vc = [[self alloc] init];
        return vc;
    }];
}
```

**Comment by JerseyBro** [comment]
人家不是说做了测试了吗
**性能**
您可能会担心启动性能，因为我们在+ load方法中放入了很多注册代码。实际上，+ load方法中Bifrost的代码非常简单。我进行了一个测试，以注册10000个路由器URL和100个模块。只需再花费60毫秒。
