### ISSUE TITLE
咨询一下Mediator这个模块的理解

### ISSUE THREAD

**Issue by Jacky-LinPeng** [youzan/Bifrost#10]
本人根据demo工程，对Mediator这个有点疑惑，Home，Sale，Shop模块相互调用的话都要依赖Mediator，各个模块要将自己的协议放在Mediator里面暴露给需要的模块调用，那这个Mediator该由谁来维护？开发过程中Sale和Shop等模块是由不同团队在开发维护。我对Mediator这个有点想不通,,,求大佬分析讲解，是不是我的理解和使用姿势不对？

**Comment by jackieyk** [comment]
目前demo里的mediator是一种简化模式，多个模块把自己对外暴露的服务都放到了同一个mediator模块里。这个mediator的确是多个模块的owner共同维护的。但是考虑到mediator的结构也是基于文件夹分的比较清晰的所以迭代时的冲突不会太多，而且mediator里的文件数量很少，且每个模块对外暴露的服务的更新频次也不会太高，所以认为虽然解耦不那么彻底，但是基于ROI的考虑反而是更合适的（拆分更彻底也是有成本的）。

如果自己的团队存在要进一步解耦的情况（比如模块对外服务更新很频繁，要做更严格的对外服务代码变更的权限管控等等），也可以把mediator进一步分拆，比如拆成Home-Servcie（或者叫做HomeInterface）, Sale-Service, …… 他们共同组成Mediator这个角色（其实后端基于dubbo的服务化的架构设计也是这样，会拆分为interface和impl 2部分，对外暴露interface这一层）只是这样一来，一个app的模块数量就直接double了，维护成本也上去了。所以我们这边做了讨论后做了如demo里这样的简化。

**Comment by jackieyk** [comment]
目标demo里的是一种简化模式，多个模块把自己对外暴露的服务都放到了同一个mediator里。这个mediator的确是多个模块的owner共同维护的。但是考虑到mediator的结构也是基于文件夹分的比较清晰的，而且mediator里的文件数量很少，且每个模块对外暴露的服务的更新频次也不会太高，所以认为虽然解耦不那么彻底，但是基于ROI的考虑反而是更合适的。

如果自己的团队存在要进一步彻底解耦的情况（比如模块对外服务暴露很频繁，要做更严格的对外服务代码变更的管控等等），也可以把mediator进一步分拆，比如拆成Home-Mediator（或者叫做HomeInterface或HomeService）, Sale-Mediator, …… （其实后端基于dubbo的服务化的架构设计也是这样，会拆分为interface和impl 2部分，对外暴露interface这一层）只是这样一来，一个app的模块数量就直接double了，维护成本也上去了。所以我们这边做了讨论后做了如demo里这样的简化。

**Comment by Jacky-LinPeng** [comment]
get!  感谢大佬
