### ISSUE TITLE
help wanted：新增业务模块的bundle如何加入到主工程？

### ISSUE THREAD

**Issue by Jacky-LinPeng** [youzan/Bifrost#11]
根据demo工程架构 我新增一个Pay子模块，但是我发现该模块的Bundele资源一直加不进去，希望指导一下

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/15797691/156911564-d14892e2-1e38-4a87-b85c-12d93d01a544.png">

PayBundle无法选择加入进去
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/15797691/156911577-60620afe-b753-4c64-9478-66b62b2426d9.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/15797691/156911628-47b3d676-1a98-43d2-937e-e1e556cba4d4.png">

**Comment by jackieyk** [comment]
demo里的方式有点tricky， 细节忘了，我回头翻翻老文档
我们后来调整成了把每个module做成Pod，这样module里需要集成的资源文件，在这个module的podspec里配好就行了
这些module pod如果不需要对外发布（比如仍然在同一个git中管理），可以以dev pod的方式集成，开发过程也比价高效

**Comment by Jacky-LinPeng** [comment]
因为现在很多都用pod来管理了 很少见到demo这样的以子工程方式来集成，刚好遇到这个Bundle问题就想咨询一下...
