### ISSUE TITLE
ViewController引用Mediator中的Service算不算耦合

### ISSUE THREAD

**Issue by yutian105** [youzan/Bifrost#4]
我看几乎每个模块中都引用了Mediator中的Service这样设计是否还有优化的空间

**Comment by jackieyk** [comment]
好问题。其实一开始也是考虑通过反射等方式做到绝对的解耦的，但是后来实践中发现这是有代价的，会对质量和效率有损。所以后需也思考过“绝对解耦”的价值在哪里？是业界倡导的,还是自己团队真正需要的。demo里的形式是最终采用的方式
