### ISSUE TITLE
URL和Protocol选择问题

### ISSUE THREAD

**Issue by snilwx** [youzan/Bifrost#5]
项目中同时存在URL和Protocol两种方案，这两种方案分别在什么情况下做优先选择呢？根据参数是不是复杂参数吗？

**Comment by jackieyk** [comment]
url的独特优势是动态性和跨平台，比如iOS和Android都可以使用同样的url路由，但接口（protocol）无法跨平台。
protocol的优势是存在复杂调用及复杂数据传输能通过编译检查保证质量
所以建议有动态性和跨平台需求时用url， 复杂调用和复杂数据传输场景使用protocol
肯定有介于以上两种情况之间的灰色地带，这时可以根据团队自己的情况制定自身的规范。
