### ISSUE TITLE
关于组件化时重复引入基础库的问题？ 

### ISSUE THREAD

**Issue by snilwx** [youzan/Bifrost#6]
请教您一个关于组件化时重复引入基础库的问题，场景是这样的：

有四个功能模块，分给了四个不同的团队开发，我们只负责整合集成组件并打包成最终的APP，四个组件都是以framework的形式提供给我们的，我们这边看不到组件源码，这四个组件都会依赖相同的基础库和网络请求库，那么他们打包成framework的时候，每个framework里都会包含这些基础库和网络请求库，那么我们在最终整个这四个功能组件的时候，基础组件相当于被项目引入了4次？这样理解对吗？如果对的话，有什么方法能解决呢？

**Comment by Zhangyanshen** [comment]
将基础库和网路请求库也封装成动态库framework，然后四个团队都去依赖这2个framework应该可以，如果他们是以源码形式或者静态库的形式依赖的，你在整合打包的时候应该无法编译通过，会报重复定义，我的理解是这样的

**Comment by jackieyk** [comment]
楼上正解
